#!/bin/bash
source ./Config

OUTPUT=$(env | grep LD_LIBRARY_PATH | cut -d ";" -f 2)
PWD=$(pwd)

VARIABLE_PART=`echo $OUTPUT | cut -d "=" -f 2`
LEN=`echo $VARIABLE_PART | awk '{print length}'`

if [ "$LEN" -eq "0" ]; then
   export LD_LIBRARY_PATH=$PWD/$LIB_PATHJ:$PWD/$JSON_C_DIRECTORY
else
    export LD_LIBRARY_PATH=$PWD/$LIB_PATH:$PWD/$JSON_C_DIRECTORY:$VARIABLE_PART
fi
