#!/bin/bash
source ./Config

output=$(env | grep LD_LIBRARY_PATH | cut -d ";" -f 2)
path=$(pwd)

len=`echo $output | awk '{print length}'`

if [ "$len" -eq "0" ]; then
   export LD_LIBRARY_PATH=$path/$LIBRARY_PATH
else
    export LD_LIBRARY_PATH=$path/$LIBRARY_PATH:$OUTPUT
fi
